name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - uses: totto2727-org/monorepo/.github/actions/setup-nix@380f76bdd0f0ccc307c15ac9f48d7a7d851d1409
      - uses: totto2727-org/monorepo/.github/actions/setup-moonbit@380f76bdd0f0ccc307c15ac9f48d7a7d851d1409
        with:
          dev-shell: ci
      - uses: totto2727-org/monorepo/.github/actions/check-moonbit@380f76bdd0f0ccc307c15ac9f48d7a7d851d1409
        with:
          dev-shell: ci
